Homework1/Homework1/Models/Announcement.cs
namespace Homework1.Models
{
    public class Announcement
    {
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Text { get; set; }
        public string? ResponsiblePerson { get; set; }
        public DateTime Time { get; set; }
    }
}

Homework1/Homework1/Models/Repository.cs
namespace Homework1.Models{
    public static class Repository{
        private static List<Announcement> announcements = new();

        static Repository(){
            announcements.Add(new Announcement(){
                Id=1, 
    
                Time=DateTime.Now,
                Title="Artificial Intelligence Academic Thesis Program Begins", 
                Text="The program aims to increase competencies in the field of artificial intelligence in the defense industry, contribute to the need for qualified human resources in the sector and establish cooperation between academia and industry in the field of artificial intelligence. Students accepted to the program will be announced on October 31. Successful students will benefit from opportunities such as internship, candidate engineering program and project support in line with their competencies.", 
                ResponsiblePerson="Alican"
            });
            announcements.Add(new Announcement(){
                Id=2, 
                
                Time=DateTime.Now,
                Title="2209-A - University Students Research Projects Support Program Call", 
                Text="2209-A University Students Research Projects Support Program 2024 1st semester call is open for application. Applications can be made via TUBITAK Management Information System (tybs.tubitak.gov.tr) until 17.30 on November 01, 2024.", 
                ResponsiblePerson="Nurcan"
            });
            announcements.Add(new Announcement(){
                Id=3, 
                
                Time=DateTime.Now,
                Title="4001 National and International Competition/Event Participation Support 2nd Call", 
                Text="The 2nd call for 4001 National and International Competition/Event Participation Support, whose first call period was held between August 2 and September 30, was published on October 1, 2024 and opened for application.", 
                ResponsiblePerson="Gülcan"
            });
                announcements.Add(new Announcement(){
                Id=4, 
                
                Time=DateTime.Now,
                Title="Adaptation to University Life Program", 
                Text="An orientation program has been organized for our new students to get to know university life and Sakarya University more closely; the topics, programs, people and places to be informed are attached.", 
                ResponsiblePerson="Mehmetcan"
            });
        }
       public static List<Announcement> Announcements => announcements;

        public static void CreateAnnouncement(Announcement announcement)
        {
            announcement.Id = announcements.Count + 1;
            announcement.Time = DateTime.Now;
            announcements.Add(announcement);
        }

        public static Announcement? GetById(int Id){
            return announcements.FirstOrDefault(a => a.Id == Id);
        }
        
    }
}

Homework1/Homework1/Controllers/AddAnnouncementsController.cs
using Microsoft.AspNetCore.Mvc; 
using Homework1.Models;
namespace Homework1.Controllers{
    public class AddAnnouncementsController : Controller {
         [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Announcement announcement)
        {
            if (ModelState.IsValid)
            {
                Repository.CreateAnnouncement(announcement);
                return RedirectToAction("Index", "Announcements");
            }
            return View(announcement);
        }
        
        
    }
}

Homework1/Homework1/Controllers/AnnouncementsController.cs
using Microsoft.AspNetCore.Mvc;
using Homework1.Models;

namespace Homework1.Controllers{
    public class AnnouncementsController : Controller {
        public IActionResult Index(){
           var announcements = Repository.Announcements;
           ViewBag.AnnouncementCount = announcements.Count;
            return View(announcements);
        }
    }
}

Homework1/Homework1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Homework1.Models;
namespace Homework1.Controllers{
    public class HomeController : Controller {
        public IActionResult Index(){
            return View();
        }
    }
}

Homework1/Homework1/Views/AddAnnouncements/Index.cshtml

@model Homework1.Models.Announcement

<div class="form-container">
    <h2>Add Announcement</h2>
    <form method="post" action="/AddAnnouncements/Index">
        <div class="mb-3">
            <label asp-for="Title" class="form-label">Title</label>
            <input asp-for="Title" class="form-control" name ="Title"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Text" class="form-label">Text</label>
            <textarea asp-for="Text" class="form-control"name="Text"></textarea>
            <span asp-validation-for="Text" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="ResponsiblePerson" class="form-label">Responsible Person</label>
            <input asp-for="ResponsiblePerson" class="form-control" name="ResponsiblePerson" />
            <span asp-validation-for="ResponsiblePerson" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Add Announcement</button>
    </form>
</div>
<footer body style="background-color:beige">
  <p body style="color: black; margin-top: auto; text-align: center;">Author: Tuna Parlak ID:B221202022</p>
</footer>

Homework1/Homework1/Views/Announcements/Index.cshtml

@model List<Homework1.Models.Announcement>





<h2>Announcements:</h2>

<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Text</th>
            <th>Responsible Person</th>
            <th>Time</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var announcement in Model)
        {
            <tr>
                <td>@announcement.Title</td>
                <td>@announcement.Text</td>
                <td>@announcement.ResponsiblePerson</td>
                <td>@announcement.Time</td>
            </tr>
        }
    </tbody>
</table>
<h1>Total Announcements:@ViewBag.AnnouncementCount</h1>
<footer body style="background-color:beige">
  <p body style="color: black; margin-top: auto; text-align: center;">Author: Tuna Parlak ID:B221202022</p>
</footer>

Homework1/Homework1/Views/Home/Index.cshtml
<h1 body style="text-align: center;">Welcome to main page.</h1>
<p id="datetime"></p>

<script>
  var now = new Date();
  var datetime = now.toLocaleString();
  document.getElementById("datetime").innerHTML = datetime;
</script>
@Html.ActionLink("Add Announcements","Index","AddAnnouncements")<br>
@Html.ActionLink("All Announcements","Index","Announcements")
  
<footer body style="background-color:beige">
  <p body style="color: black; margin-top: auto; text-align: center;">Author: Tuna Parlak ID:B221202022</p>
</footer>